# TestFlow — Selenium Python Export Template
#
# This template is processed by export-engine.js.
# Placeholders: {{flowName}}, {{steps}}, {{imports}}, {{testData}}

# ── Simple Script Template ──────────────────────────────────

SIMPLE_SCRIPT = """
# Generated by TestFlow — Test Automation IDE
# Flow: {{flowName}}
# Date: {{timestamp}}

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import time

# Test Data
{{testDataBlock}}

def run_test():
    driver = webdriver.Chrome()
    wait = WebDriverWait(driver, 10)

    try:
{{stepsBlock}}

        print("✅ Test passed!")
    except Exception as e:
        print(f"❌ Test failed: {e}")
        driver.save_screenshot("error_screenshot.png")
        raise
    finally:
        driver.quit()

if __name__ == "__main__":
    run_test()
"""

# ── Page Object Model Template ──────────────────────────────

POM_PAGE = """
# Generated by TestFlow — Test Automation IDE
# Page Object: {{pageName}}

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class {{pageClassName}}:
    # Locators
{{locatorConstants}}

    def __init__(self, driver):
        self.driver = driver
        self.wait = WebDriverWait(driver, 10)

{{pageMethods}}
"""

POM_TEST = """
# Generated by TestFlow — Test Automation IDE
# Test: {{flowName}}

from selenium import webdriver
{{pageImports}}

# Test Data
{{testDataBlock}}

def test_{{flowSlug}}():
    driver = webdriver.Chrome()

    try:
{{pomStepsBlock}}

        print("✅ Test passed!")
    except Exception as e:
        print(f"❌ Test failed: {e}")
        driver.save_screenshot("error_screenshot.png")
        raise
    finally:
        driver.quit()

if __name__ == "__main__":
    test_{{flowSlug}}()
"""
